import { useEffect } from 'react';
import { Redirect } from 'expo-router';
import { useDocumentStore } from '@/store/document-store';
import { useAuthStore } from '@/store/auth-store';
import { sampleDocuments } from '@/mocks/sample-documents';

export default function Index() {
  const documents = useDocumentStore(state => state.documents);
  const addDocument = useDocumentStore(state => state.addDocument);
  const isAuthenticated = useAuthStore(state => state.isAuthenticated);
  const hasCompletedOnboarding = useAuthStore(state => state.hasCompletedOnboarding);
  
  // Add sample documents only if there are no documents yet
  useEffect(() => {
    if (documents.length === 0 && isAuthenticated) {
      // Add sample documents without their IDs, createdAt, and updatedAt
      // as those will be generated by the addDocument function
      sampleDocuments.forEach(doc => {
        const { id, createdAt, updatedAt, companyId, ...docWithoutIds } = doc;
        addDocument(docWithoutIds);
      });
    }
  }, [isAuthenticated]);
  
  // Redirect based on authentication state
  if (!hasCompletedOnboarding) {
    return <Redirect href="/onboarding" />;
  }
  
  if (!isAuthenticated) {
    return <Redirect href="/(auth)" />;
  }
  
  // Redirect to the main tab
  return <Redirect href="/(tabs)" />;
}